import adeleye from "../images/Adeleye.png";import basit from "../images/Basit.png";import dots from "../images/dots.png";import edu1 from "../images/edu1.png";import edu2 from "../images/edu2.png";import edu3 from "../images/edu3.png";import empowering from "../images/Empowering.png";import enroll from "../images/Enroll.png";import experience from "../images/Experience.png";import feedback from "../images/feedbacksvg.png";import growth from "../images/growth.png";import home from "../images/home.png";import joshua from "../images/Joshua.png";import leftPlan from "../images/left-plan.png";import mitImage from "../images/mit-img.png";import mit from "../images/mit.png";import python from "../images/python.png";import rightPlan from "../images/right-plan.png";import scratch from "../images/scratch.png";import sliderImage from "../images/sliderimg.png";import subomi from "../images/Subomi.png";import tokunbo from "../images/Tokunbo.jpg";import uiUx from "../images/uiux.png";import values from "../images/values.png";import webImage from "../images/web-img.png";import web from "../images/web.png";import roblox from "../images/roblox.png";import advanced from "../images/advanced-img.png";import beginners from "../images/beginners-img.png";import intermediate from "../images/intermediate-img.png";import plans from "../images/plans-deg.png";import beginnerSvg from "../images/beginner.png";import intermediateSvg from "../images/intermediate.png";import advancedSvg from "../images/advanced.png";import beginnerActive from "../images/beginner-a.png";import intermediateActive from "../images/intermediate-a.png";import advancedActive from "../images/advanced-a.png";import otherPlans from "../images/plans.png";import joinLeft from "../images/join-left.png";import joinRight from "../images/join-right.png";import whychoose from "./whychoose.png";import instructor from "../images/instructor.png";import brochureImg from "../images/brochure.png"
export {adeleye,basit,dots,edu1,edu2,edu3,empowering,enroll,experience,feedback,growth,home,joshua,leftPlan,mitImage,mit,python,rightPlan,roblox,scratch,sliderImage,subomi,tokunbo,uiUx,values,webImage,web,advanced,beginners,intermediate,plans,beginnerSvg,intermediateSvg,advancedSvg,beginnerActive,intermediateActive,advancedActive,otherPlans,joinLeft,joinRight,whychoose,instructor,brochureImg}









